src/objects/A__c.object
<CustomObject>
    <label>A</label>
    <nameField>
        <label>A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/B__c.object
<CustomObject>
    <label>B</label>
    <nameField>
        <label>B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/C__c.object
<CustomObject>
    <fields>
        <fullName>A_Associate__c</fullName>
        <label>A</label>
        <referenceTo>A__c</referenceTo>
        <relationshipLabel>Cs</relationshipLabel>
        <relationshipName>Cs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>B_Associate__c</fullName>
        <label>B</label>
        <referenceTo>B__c</referenceTo>
        <relationshipLabel>Cs</relationshipLabel>
        <relationshipName>Cs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>C</label>
    <nameField>
        <label>C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewTodaysTest.cls
public class NewTodaysTest {
               
       public static void methodOnCustomC(){
        List<C__c> customList = new List<C__c>([select Name ,
                                                A_Associate__r.Name,
                                                B_Associate__r.Name
                                               
                                                from C__c
                                                where name = 'John']);
    for(C__c customC : customList){
        system.debug('child name'+customC.name+'A name '+customC.A_Associate__r.name);
    }
    } 
}